{
 "title": "CDN Metrics Dashboard",
 "tags": [
  "cdn",
  "prometheus",
  "edge",
  "origin"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Origin Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total",
     "legendFormat": "{{method}} {{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Edge Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total",
     "legendFormat": "{{instance}} {{method}} {{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Edge Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "edge_cache_hits_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Edge Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "edge_cache_misses_total", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}